### ISSUE TITLE
请问配置文件在哪呢

### ISSUE THREAD

**Issue by MenardiC** [Pzzzzz5142/Pbot#2]

**Comment by Pzzzzz5142** [comment]
（打游戏打忘了没看到，，，现在放上去了。

**Comment by Pzzzzz5142** [comment]
<img width="380" alt="image" src="https://user-images.githubusercontent.com/31173671/105446076-567b8d00-5cac-11eb-868e-6717abfef8db.png">
主要bot直连p站风控邮件太多了（（（
